Added unsquashfs_all.sh script. Uncommented squashfs-3.2-r2-lzma build in src/others/Makefile.
git-svn-id: http://firmware-mod-kit.googlecode.com/svn/trunk@188 5c1471b0-2a1b-0410-b4f4-f33460ac40b9

diff --git a/trunk/src/jffs2/unjffs2 b/trunk/src/jffs2/unjffs2
--- a/trunk/src/jffs2/unjffs2
+++ b/trunk/src/jffs2/unjffs2
@@ -1,4 +1,8 @@
 #!/bin/bash
+# Script to mount a JFFS2 image and copy the file system's files to a destination directory.
+#
+# Craig Heffner
+# 27 August 2011
 
 IMG="$1"
 DST="$2"
@@ -17,11 +21,13 @@ fi
 
 TMP="/tmp/$DST"
 
+#Make sure required modules are loaded
 modprobe mtdblock
 modprobe mtdchar
 modprobe mtdram
 modprobe mtd
 
+#Create destination and temporary mount directories
 mkdir $DST && mkdir $TMP
 
 if [ $? == 0 ]
@@ -31,11 +37,18 @@ then
 		mknod $BLOCK b 31 0
 	fi
 
+	#Copy JFSS2 image to MTD block
 	dd if="$IMG" of=$BLOCK 2>/dev/null && mount -t jffs2 $BLOCK $TMP
 
 	if [ $? == 0 ]
 	then
+		#Copy files from mounted directory to destination directory, then unmount
 		cp -vR $TMP/* $DST
 		umount $TMP && rm -rf $TMP
+		exit 0
+	else
+		echo "Failed to mount $IMG to $BLOCK"
 	fi
 fi
+
+exit 1
